# Generated by Django 5.0.4 on 2024-04-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='fecha update')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=200)),
                ('anios', models.IntegerField(default=0)),
                ('inicio_date', models.DateTimeField(verbose_name='inicio trabajo')),
                ('final_date', models.DateTimeField(verbose_name='final trabajo')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvs.persona')),
            ],
        ),
    ]
